### ISSUE TITLE
Trying to Install on Magento 2.4.3-p1 via composer - main.CRITICAL: Error

### ISSUE THREAD

**Issue by BeenDelux** [mollie/magento2#490]
System Info:
Magento 2.4.3-p1 Open Source, nginx, php 7.4, mariaDB

Steps to reproduce
1. Install Mollie Extension via Composer
`composer require mollie/magento2`

(Module Version 2.6.0 mollie/payment will be installed)
(Module mollie-api-php will be installed)

2. Run Magento commands
`php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:Deploy
php bin/magento cache:clean`

3. Navigate to Shops -> Configuration -> Error 

`main.CRITICAL: Error: Class 'Mollie\Payment\Plugin\Config\LoadCorrectGroup' not found in /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php:60
Stack trace:
#0 /var/www/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create()
#1 /var/www/magento2/vendor/magento/framework/Interception/PluginList/PluginList.php(174): Magento\Framework\ObjectManager\ObjectManager->get()
#2 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(119): Magento\Framework\Interception\PluginList\PluginList->getPlugin()
#3 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Model\Config\Loader\Interceptor->Magento\Framework\Interception\{closure}()
#4 /var/www/magento2/generated/code/Magento/Config/Model/Config/Loader/Interceptor.php(23): Magento\Config\Model\Config\Loader\Interceptor->___callPlugins()
#5 /var/www/magento2/vendor/magento/module-config/Model/Config.php(648): Magento\Config\Model\Config\Loader\Interceptor->getConfigByPath()
#6 /var/www/magento2/vendor/magento/module-config/Model/Config.php(503): Magento\Config\Model\Config->_getConfig()
#7 /var/www/magento2/vendor/magento/module-config/Model/Config.php(690): Magento\Config\Model\Config->load()
#8 /var/www/magento2/vendor/magento/module-paypal/Helper/Backend.php(62): Magento\Config\Model\Config->getConfigDataValue()
#9 /var/www/magento2/vendor/magento/module-paypal/Model/Config/Rules/Reader.php(54): Magento\Paypal\Helper\Backend->getConfigurationCountryCode()
#10 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Paypal\Model\Config\Rules\Reader->__construct()
#11 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#12 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#13 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#14 /var/www/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create()
#15 /var/www/magento2/vendor/magento/framework/View/Element/BlockFactory.php(46): Magento\Framework\ObjectManager\ObjectManager->create()
#16 /var/www/magento2/vendor/magento/framework/View/Layout/Generator/Block.php(272): Magento\Framework\View\Element\BlockFactory->createBlock()
#17 /var/www/magento2/vendor/magento/framework/View/Layout/Generator/Block.php(252): Magento\Framework\View\Layout\Generator\Block->getBlockInstance()
#18 /var/www/magento2/vendor/magento/framework/View/Layout/Generator/Block.php(229): Magento\Framework\View\Layout\Generator\Block->createBlock()
#19 /var/www/magento2/vendor/magento/framework/View/Layout/Generator/Block.php(134): Magento\Framework\View\Layout\Generator\Block->generateBlock()
#20 /var/www/magento2/vendor/magento/framework/View/Layout/GeneratorPool.php(93): Magento\Framework\View\Layout\Generator\Block->process()
#21 /var/www/magento2/vendor/magento/framework/View/Layout.php(365): Magento\Framework\View\Layout\GeneratorPool->process()
#22 /var/www/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(32): Magento\Framework\View\Layout->generateElements()
#23 /var/www/magento2/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#24 /var/www/magento2/vendor/magento/framework/View/Page/Builder.php(65): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#25 /var/www/magento2/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#26 /var/www/magento2/vendor/magento/framework/View/Layout.php(271): Magento\Framework\View\Layout\Builder->build()
#27 /var/www/magento2/vendor/magento/framework/View/Layout.php(896): Magento\Framework\View\Layout->build()
#28 /var/www/magento2/vendor/magento/module-backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout->getBlock()
#29 /var/www/magento2/vendor/magento/module-config/Controller/Adminhtml/System/Config/Edit.php(57): Magento\Backend\Model\View\Result\Page->setActiveMenu()
#30 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Controller\Adminhtml\System\Config\Edit->execute()
#31 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callParent()
#32 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}()
#33 /var/www/magento2/generated/code/Magento/Config/Controller/Adminhtml/System/Config/Edit/Interceptor.php(23): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callPlugins()
#34 /var/www/magento2/vendor/magento/framework/App/Action/Action.php(111): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->execute()
#35 /var/www/magento2/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#36 /var/www/magento2/vendor/magento/module-config/Controller/Adminhtml/System/AbstractConfig.php(69): Magento\Backend\App\AbstractAction->dispatch()
#37 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch()
#38 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callParent()
#39 /var/www/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}()
#40 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#41 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}()
#42 /var/www/magento2/generated/code/Magento/Config/Controller/Adminhtml/System/Config/Edit/Interceptor.php(32): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callPlugins()
#43 /var/www/magento2/vendor/magento/framework/App/FrontController.php(245): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->dispatch()
#44 /var/www/magento2/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#45 /var/www/magento2/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#46 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#47 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#48 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#49 /var/www/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#50 /var/www/magento2/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#51 /var/www/magento2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#52 /var/www/magento2/pub/index.php(29): Magento\Framework\App\Bootstrap->run()`

Expected behavior
Can view and configure settings at shops -> confiiguration

Actual behavior
see error above

Maybe it depends to the mollie-api-php module? Are there further steps needed that i am missing after command composer require mollie/mollie-api-php?

Hope anyone can help me to solve this issue.

Thanks and Best Regards,
Beendeluxe

**Comment by BeenDelux** [comment]
This issue can be closed. I figured out myself and could solve this issue.

Solution:
php services needs to restarted after installation process.

All good now. 

Best Regards,
Beendeluxe
