### ISSUE TITLE
[ISSUE] When clicking "Mark as paid" we get "An error has happened during application run."

### ISSUE THREAD

**Issue by simonmaass** [mollie/magento2#659]
**Describe the bug**
When clicking "Mark as paid" we get "An error has happened during application run."

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6
- *Open source/Enterprise/B2b*: open source
- *Mollie version number (Check configuration)*: 2.25.0

**To Reproduce**
1. Create Order with mollie payment link
2. Click on "Mark as paid"

**Expected behavior**
Create new order that is marked as paid and old order is canceled

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**
<img width="1704" alt="image" src="https://github.com/mollie/magento2/assets/32599710/e55b29ac-07c8-44fb-8177-06a0aec7daee">

**Additional context**

```
TypeError: Dhl\Paket\Model\AdditionalFee\AdditionalFeeProvider::getAmounts(): Argument #1 ($storeId) must be of type int, string given, called in vendor/dhl/module-carrier-paket/Model/AdditionalFee/AdditionalFeeConfiguration.php on line 46 and defined in vendor/dhl/module-carrier-paket/Model/AdditionalFee/AdditionalFeeProvider.php:27
Stack trace:
#0 vendor/dhl/module-carrier-paket/Model/AdditionalFee/AdditionalFeeConfiguration.php(46): Dhl\Paket\Model\AdditionalFee\AdditionalFeeProvider->getAmounts('1')
#1 vendor/dhl/module-carrier-paket/Model/AdditionalFee/AdditionalFeeConfiguration.php(83): Dhl\Paket\Model\AdditionalFee\AdditionalFeeConfiguration->calculateAdjustmentAmount(Object(Magento\Quote\Model\Quote\Interceptor))
#2 vendor/netresearch/module-shipping-core/Model/AdditionalFee/AdditionalFeeManagement.php(46): Dhl\Paket\Model\AdditionalFee\AdditionalFeeConfiguration->isActive(Object(Magento\Quote\Model\Quote\Interceptor))
#3 vendor/netresearch/module-shipping-core/Model/AdditionalFee/Total.php(109): Netresearch\ShippingCore\Model\AdditionalFee\AdditionalFeeManagement->isActive(Object(Magento\Quote\Model\Quote\Interceptor))
#4 vendor/magento/module-quote/Model/Quote/TotalsCollector.php(261): Netresearch\ShippingCore\Model\AdditionalFee\Total->collect(Object(Magento\Quote\Model\Quote\Interceptor), Object(Magento\Quote\Model\ShippingAssignment), Object(Magento\Quote\Model\Quote\Address\Total))
#5 vendor/magento/module-quote/Model/Quote/TotalsCollector.php(156): Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals(Object(Magento\Quote\Model\Quote\Interceptor), Object(Magento\Quote\Model\Quote\Address))
#6 vendor/magento/module-quote/Model/Quote.php(2021): Magento\Quote\Model\Quote\TotalsCollector->collect(Object(Magento\Quote\Model\Quote\Interceptor))
#7 generated/code/Magento/Quote/Model/Quote/Interceptor.php(743): Magento\Quote\Model\Quote->collectTotals()
#8 vendor/magento/module-sales/Model/AdminOrder/Create.php(1634): Magento\Quote\Model\Quote\Interceptor->collectTotals()
#9 vendor/magento/module-sales/Model/AdminOrder/Create.php(1622): Magento\Sales\Model\AdminOrder\Create->collectRates()
#10 vendor/magento/module-sales/Model/AdminOrder/Create.php(596): Magento\Sales\Model\AdminOrder\Create->collectShippingRates()
#11 vendor/mollie/magento2/Service/Order/Reorder.php(160): Magento\Sales\Model\AdminOrder\Create->initFromOrder(Object(Magento\Sales\Model\Order\Interceptor))
#12 vendor/mollie/magento2/Service/Order/Reorder.php(125): Mollie\Payment\Service\Order\Reorder->recreate(Object(Magento\Sales\Model\Order\Interceptor))
#13 vendor/mollie/magento2/Controller/Adminhtml/Action/MarkAsPaid.php(59): Mollie\Payment\Service\Order\Reorder->createAndInvoice(Object(Magento\Sales\Model\Order\Interceptor))
#14 vendor/magento/framework/Interception/Interceptor.php(58): Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid->execute()
#15 vendor/magento/framework/Interception/Interceptor.php(138): Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor->___callParent('execute', Array)
#16 vendor/magento/framework/Interception/Interceptor.php(153): Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor->Magento\Framework\Interception\{closure}()
#17 generated/code/Mollie/Payment/Controller/Adminhtml/Action/MarkAsPaid/Interceptor.php(23): Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor->___callPlugins('execute', Array, Array)
#18 vendor/magento/framework/App/Action/Action.php(111): Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor->execute()
#19 vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#20 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#21 vendor/magento/framework/Interception/Interceptor.php(138): Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor->___callParent('dispatch', Array)
#22 vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 vendor/magento/framework/Interception/Interceptor.php(153): Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 generated/code/Mollie/Payment/Controller/Adminhtml/Action/MarkAsPaid/Interceptor.php(32): Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor->___callPlugins('dispatch', Array, Array)
#26 vendor/magento/framework/App/FrontController.php(245): Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor), Object(Magento\Framework\App\Request\Http))
#28 vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Mollie\Payment\Controller\Adminhtml\Action\MarkAsPaid\Interceptor))
#29 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#30 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#31 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#33 vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#34 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#35 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#36 vendor/justbetter/magento2-sentry/Plugin/GlobalExceptionCatcher.php(89): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#37 vendor/magento/framework/Interception/Interceptor.php(135): JustBetter\Sentry\Plugin\GlobalExceptionCatcher->aroundLaunch(Object(Magento\Framework\App\Http\Interceptor), Object(Closure))
#38 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#39 generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, NULL)
#40 vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#41 pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#42 {main}
```

**Comment by simonmaass** [comment]
https://github.com/netresearch/dhl-module-carrier-paket/issues/11

**Comment by Frank-Magmodules** [comment]
Hello, @simonmaass! It appears that there is indeed a conflict with the DHL plugin. We will investigate this matter and provide you with more information regarding the plugin responsible for this issue.

**Comment by Frank-Magmodules** [comment]
Hello there, @simonmaass! I also came across your message on the [DHL Github repository](https://github.com/netresearch/dhl-module-carrier-paket/issues/11) and noticed that their comment [confirmed](https://github.com/netresearch/dhl-module-carrier-paket/issues/11#issuecomment-1594592400) that the problem has been resolved from their side.  Could you please confirm this by closing this issue if that's the case? Thanks a lot!

**Comment by simonmaass** [comment]
Hey @Frank-Magmodules - will do as soon as new version for https://github.com/netresearch/dhl-shipping-m2 is released!

**Comment by Frank-Magmodules** [comment]
Allright @simonmaass , let me know, thanks!

**Comment by Frank-Magmodules** [comment]
Hi There @simonmaass , I just noticed that DHL updated [their plugin](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.9.0), can you confirm that this issue can be closed now?

**Comment by simonmaass** [comment]
Hey @Frank-Magmodules - we actually installed the update yesterday and it works.

We actually noticed another problem with the "mark as paid" functionality:

When we marked an order as paid the order was "Panding Payment" and the new order that was created after clicking the button had the same order status and we are not able to change that status...

**Comment by Frank-Magmodules** [comment]
Sure, @simonmaass, I'll look into that and get back to you shortly!

**Comment by Frank-Magmodules** [comment]
Hello @simonmaass, I'm pleased to inform you that the "mark as paid" function has been successfully resolved in the [most recent release](https://github.com/mollie/magento2/releases/tag/v2.30.0). We are currently closing this matter, but please don't hesitate to reopen it if necessary.
